openedx/frontend-app-learner-portal-programs

src/components/Links/Links.jsx
src/components/Links/Links.test.jsx
src/components/Links/__snapshots__/Links.test.jsx.snap

[ENT-1817](https://openedx.atlassian.net/browse/ENT-1817)

add a dumb component to render links

---

package-lock.json
package.json
src/components/Hero/Hero.jsx
src/components/Hero/Hero.scss
src/components/Hero/Hero.test.jsx
src/components/Hero/__snapshots__/Hero.test.jsx.snap
src/components/Layout/Layout.scss
src/pages/index.jsx

The purpose of this PR is to add a hero component that will display name, course title and logo of the enterprise organization.
Below is the example snapshot, how the component would look like:
[ENT-1814](https://openedx.atlassian.net/browse/ENT-1814)

Add a hero component

---

src/components/CourseCard/CompletedCourseCard.jsx
src/components/CourseCard/CourseCard.scss
src/components/CourseCard/InProgressCourseCard.jsx
src/components/CourseCard/UpcomingCourseCard.jsx
src/components/Hero/Hero.jsx
src/components/Hero/Hero.scss
src/components/Hero/__snapshots__/Hero.test.jsx.snap
src/pages/index.jsx

Received some minor feedback/updates from UX with regard to the hero and course card components. This PR addresses those style updates.

Style updates for hero and course cards

---

package-lock.json
package.json
src/components/DashboardHome/DashboardHome.jsx
src/components/DashboardHome/MainContent.jsx

Description: This PR moves the Sidebar component below the InProgressCourseCard for mobile devices
JIRA: https://openedx.atlassian.net/browse/ENT-1920

Added Media Query for Sidebar

---

src/components/CourseSection/CourseSection.jsx
src/components/CourseSection/CourseSection.scss
src/components/DashboardHome/DashboardHome.jsx
src/components/Layout/Layout.scss

Adds collapsible functionality to the course sections using the `Collapsible` component from Paragon.

Add collapsible course sections

---

src/components/DashboardHome/MainContent.jsx

This reverts commit 7835c595577c6c1903d8d891d00a2b05d5a05773.

Revert "Adding all the console logging! (#40)"

---

src/components/CourseCard/EmailSettingsModal.jsx
src/data/actions/emailSettings.js

Just taking a hack at this. Open to feedback!

Implementing async/await refactor

---

package-lock.json
package.json
src/components/DashboardHome/DashboardHome.jsx
src/components/Layout/Layout.jsx

This PR upgrades the site header component to bring in the skip nav a11y change.

Add skip nav link to header

---

gatsby-node.js
plugins/gatsby-source-wagtail/schema/types.gql
plugins/gatsby-source-wagtail/test/mock.json
src/components/masters/program/ProgramPage.jsx
src/components/masters/program/sidebar/Sidebar.jsx
src/components/masters/program/sidebar/tests/__snapshots__/Sidebar.test.jsx.snap

This is (hopefully) the last piece of the program page puzzle. This wires up the "Manage Your Degree" section of the sidebar to a designer instance. Example:

Wire up program homepage section to portal-designer

---

.env.development
gatsby-config.js

Disables it for local and sandbox envs

Make path prefixing flagable

---

src/components/masters/programs-list/ProgramListPage.jsx

We were having an issue, due to the new routing, that broke the url redirect, causing urls like `/<institution>/<institution>/<program>` instead of `/<institution>/<program>`.
I believe this also fixes the trailing slash problem but it needs to be tested on stage.

Fix the url redirect

---

package-lock.json
package.json
src/common/utils.js

Straight copy/paste from payment MFE.

 Adding utils.js file for snake_case to camelCase object conversion

---

src/common/features.js
src/components/common/course-enrollments/course-cards/BaseCourseCard.jsx
src/components/common/course-enrollments/course-cards/InProgressCourseCard.jsx

This PR is part 1 of supporting the "Move to complete" UI functionality. It adds support for enabling features by specifying a query parameter in the URL, and displays the "Move to complete" button in the dropdown is the "move_to_complete" feature is enabled in the URL query parameter.

Add query param feature flags, 'Move to complete' button on course cards

---

src/components/common/course-enrollments/course-cards/CompletedCourseCard.jsx

Ensure proper spacing for completed course cards as well.

Another small margin fix/cleanup

---

gatsby-config.js
gatsby-node.js
package-lock.json
package.json
src/components/program/ProgramPage.jsx
src/components/program/hero/Hero.jsx
src/components/program/hero/index.js
src/components/program/hero/styles/Hero.scss
src/components/program/hero/tests/Hero.test.jsx
src/components/program/hero/tests/__snapshots__/Hero.test.jsx.snap

Ticket: [ENT-2351](https://openedx.atlassian.net/browse/ENT-2351)
This PR does the following:
* Only fetches for ProgramPage pages during build
* Adds a custom `Hero` component in place of the common one. It is an exact copy of the `Hero` that was in the base components package.

fix: add custom hero

---

src/components/program/sidebar/ProgramSidebar.jsx
src/components/program/sidebar/tests/__snapshots__/ProgramSidebar.test.jsx.snap

@edx/masters-devs-cosmonauts Please review.
This would help update the link to Masters learner specific support page at https://support.edx.org/hc/en-us/sections/360007968853-Master-s-student-help

MST-241 Update the link to point to Masters student support page

---

openedx.yaml

Added an openedx.yaml to frontend-app-learner-portal-programs .

EDUCATOR-4753 - Adding an openedx.yaml file

---

package-lock.json
package.json

[MST-592](https://openedx.atlassian.net/browse/MST-592)

[MST-592] Remove axios

---

package-lock.json
package.json
src/components/programs-list/tests/__snapshots__/ProgramListPage.test.jsx.snap

This version corrects the ICP link in the footer

[MST-1000] Bump footer to 3.1.3

---

src/components/layout/Layout.jsx
src/components/program/ProgramPage.jsx
src/components/programs-list/ProgramListPage.jsx

We should not on call page events in components for the tracking gets called multiple times

fix: Call page event tracking only on the page itself.

---

.github/workflows/node-ci.yml
.npmignore
.travis.yml

**Issue:** [BOM-2899](https://openedx.atlassian.net/browse/BOM-2899)
- Replaced the `Travis` checks with `GitHub CI`.

BOM-2899: Replace Travis with GitHub CI

---

src/components/program/ProgramPage.jsx
src/components/program/TabularView.jsx
src/components/program/data/reducer.js

Console errors were found during testing it has been fixed along with code indent improvements.

fix: console warnings fixes

---

src/components/program/TabularView.jsx
src/components/program/tab-components/CommunityTab.jsx
src/components/program/tab-components/JourneyTab.jsx

https://openedx.atlassian.net/browse/TNL-9496
Padding fixes are added in tabular view to match Figma mockups. 
screenshots will be added from staging after the PR merge.

tab style fixes

---

src/components/program/ProgramPage.jsx

live tab configured alone was rendering unusual UI behavior and that issues is fixed in this PR
https://user-images.githubusercontent.com/67791278/154243868-65d56586-06e7-4dcc-9c0f-893cfa6e95ed.mov

live tab rendering issue

---

package-lock.json
package.json
src/components/program/hero/styles/Hero.scss

https://openedx.atlassian.net/browse/MST-1336

[MST-1336] Upgrade paragon to 19.x

---

src/components/programs-list/tests/__snapshots__/ProgramListPage.test.jsx.snap

Snapshots Updated

---

package-lock.json
package.json
src/components/programs-list/tests/__snapshots__/ProgramListPage.test.jsx.snap

feat: update footer for CPRA
