openedx/frontend-app-learner-portal-programs

.travis.yml
Makefile

My only concern with this is the Gatsby cache breaking. I'm not sure what travis caches, or how they would interact, but I suppose if it becomes a problem we could also add a `clean` step.

Add build to Travis to catch more errors.

---

package-lock.json
package.json
src/components/Layout/Layout.scss

There is a new major version of the @edx/edx-bootstrap theme. The new theme includes updates that the arch teach has been working on alongside UX. The new theme more closely resembles the styles that we're using in Prospectus (e.g., updating typography to use Georgia font).
Because UX and arch wants to move more our site to use this new theme, we should consider bumping the version of @edx/edx-bootstrap theme for this project.
While there are still updates being made to the new @edx/edx-bootstrap theme, we could start using it in this project and ensure we keep the package up to date with the latest version.

Upgrade @edx/edx-bootstrap to updated theme

---

.travis.yml

Travis was doing the build step after success, which means it wasn't reporting the build errors properly (whoops!).

Fix travis to report build errors.

---

src/components/CourseCard/CompletedCourseCard.jsx

Looks like I missed removing the prop type definition for `grade` in `CompletedCourseCard` now that we're no longer showing final grade.

Remove grade prop-type

---

src/components/CourseSection/CourseSection.jsx
src/components/DashboardHome/DashboardHome.jsx
src/components/DashboardHome/DashboardHome.scss
src/components/DashboardHome/sampleApiResponse.js
src/pages/index.jsx

[ENT-1816](https://openedx.atlassian.net/browse/ENT-1816)
This PR accomplishes the following:
1. Adds a `<DashboardHome>` component that contains the hero, main content, and sidebar areas. It is a child of the `<Layout>` component in `pages/index.jsx`.
2. Creates a new file `sampleApiResponse.js` that contains a sample API response that matches the format in the document that was shared earlier. The `DashboardHome` component reads from this file, and groups enrollments by status ('in-progress', 'upcoming', or 'completed'), which is what we will expect from the API endpoint.
3. Simulates the loading state while waiting for the API response by including a spinner (the one used on the new profile MFE) in the main content area.
4. Adds a `CourseSection` component that renders each course …

Create DashboardHome and CourseSection components

---

gatsby-node.js
src/pages/app.jsx
src/pages/index.jsx

Description: This PR adds routes available only to logged-in users.
JIRA: https://openedx.atlassian.net/browse/ENT-1805
Testing Instructions:
1. Run the application by npm i and then npm start in devstack
2: Browse to http://localhost:8734/ and verify that you see the dashboard home
3: Browse to http://localhost:8734/app/1 and verify that you are redirected to the lms login page
4: Once logged in to lms browse to http://localhost:8734/app/1 and verify that you can see the dashboard 
Server environment pre-requisites: The following variable must be defined in the OS environment:
BASE_URL
LMS_BASE_URL
LOGIN_URL
LOGOUT_URL
CSRF_TOKEN_API_PATH
REFRESH_ACCESS_TOKEN_ENDPOINT
ACCESS_TOKEN_COOKIE_NAME
USER_INFO_COOKIE_NAME
For sample values for the above variable refer to: …

added client only routes

---

src/components/CourseCard/BaseCourseCard.jsx
src/components/CourseCard/CompletedCourseCard.jsx
src/components/CourseCard/EmailSettingsModal.jsx
src/components/DashboardHome/__snapshots__/Sidebar.test.jsx.snap
src/components/DashboardHome/sampleLinks.js
src/components/Links/Links.jsx
src/components/Links/__snapshots__/Links.test.jsx.snap
src/pages/app.jsx

I noticed that since we're using the `href` from `sampleLinks.js` as the `key` for each list item in the `Links` component, we were getting warnings about duplicate keys since the sample links were configured to have the same `href`. I updated the sample hrefs such that they are unique.
Another change in this PR was to switch from using Paragon's `Icon` component in our `Links` component to `FontAwesomeIcon` so we're using SVG icons everywhere.
When doing this, the tests ended up failing because the icons were being added to the font-awesome "library" in `App.jsx`. When testing components in isolation (i.e., outside of the `App.jsx` context), the required icons are not present in the font-awesome library. To fix this, I refactored our use of `FontAwesomeIcon` throughout the app where we …

Update sample links and switch to FontAwesomeIcon

---

docs/decisions/0001-record-architecture-decisions.rst
docs/decisions/0002-multi-deployment-strategy.rst

This is different than the initial design I had proposed. I think this is cleaner than having to built multi-deployment work into every app we want it in. It will now exist in the pipeline code.

Add ADR for multideployment strategy

---

src/components/DashboardHome/DashboardHome.jsx
src/components/DashboardHome/Sidebar.jsx
src/components/DashboardHome/SidebarBlock.jsx
src/components/DashboardHome/__snapshots__/Sidebar.test.jsx.snap
src/components/Links/Links.jsx

This adds a new component called `SidebarBlock`, which takes a few props: a title, a class name for the section tag renders, and children.
This PR also refactors the way the `Links` component was working. Specifically, the title and section elements have been moved out from it and into SidebarBlock for reusability.

ENT-1921 | Adding new component for sidebar items

---

README.md
gatsby-node.js

An attempt to fix auth redirect not occurring on stage and production
Running theory:
Without the trailing slash in that match, we were allowing a path starting with `/app` to be matched regardless of what followed. The side effect of this was being able to hit a path starting in `/app` but never actually hit a `<PrivateRoute` and therefore never being redirected

updating gatsby-node on how page path is matched. adding some other docs

---

package-lock.json
package.json
src/components/CourseCard/BaseCourseCard.jsx
src/components/DashboardHome/Sidebar.jsx
src/components/DashboardHome/__snapshots__/Sidebar.test.jsx.snap

To bring in the responsive typography that was released in the latest version of `@edx/edx-boostrap`, this PR upgrades that package. Also, at certain screen sizes, the buttons in the course cards were wrapping the text onto 2 lines. I've updated the responsive columns in the course card to prevent the wrapping from happening.

Upgrade @edx/edx-bootstrap, fix course card responsiveness

---

src/components/CourseCard/InProgressCourseCard.jsx
src/components/CourseCard/Notification.jsx
src/components/DashboardHome/DashboardHome.jsx
src/components/DashboardHome/SidebarBlock.jsx
src/components/DashboardHome/sampleApiResponse.js
src/components/DashboardHome/tests/__snapshots__/Sidebar.test.jsx.snap

Realized that the due date filter to only select the due dates in the next week was not handling past dates well, resulting in a negative number appearing in the due dates (e.g., "due in -4 days"). This PR primarily addresses this issue such that only dates between now and 1 week from now are shown using some of moment.js's utility functions.

fix due date filter and misc updates

---

gatsby-config.js
src/components/Layout/Layout.jsx

Pages now hold their own branding config, so we don't need to do a query in the Layout.
I moved the siteMetadata fake values into the default props for now since we don't have the plugin  and APIs ready yet. These should be set to null once those are merged.

Use props instead of query in Layout

---

.travis.yml
gatsby-config.js

This allows us to use `gatsby build` with different configurations instead of just ‘production’
eg.
```
$ ACTIVE_ENV=<env_name> npm run build
```
This also sets it so travis will use `development` for build checks when making pull requests.

Add multiple environments for build step

---

README.md
plugins/gatsby-source-wagtail/gatsby-node.js
plugins/gatsby-source-wagtail/test/dummy.json

This allows for a more independent deployment of the learn-portal, without the need for a designer backend to provide data. Feel free to edit it in any way or add more too it.

Add dummy branding data to portal

---

plugins/gatsby-source-wagtail/gatsby-node.js
plugins/gatsby-source-wagtail/schema/types.gql

If we add this graphql schema, we won't have to only rely so much on it's field inference. This way, if a blob coming from the designer api does not have data required by the `createPages` query, that field will be `null` instead of `undefined`, and the build will no longer break.
However, we still have the freedom of adding new data to designer without explicitly adding it to this schema, as gatsby will still infer fields from the data.

Add graphql schema to gatsby

---

gatsby-config.js
gatsby-node.js

Environment variables will only ever be strings, so we need to check as
strings and not as booleans.

Fix unbranded landing page check

---

src/components/common/withAuthentication/tests/withAuthentication.test.jsx
src/components/masters/programs-list/ProgramListPage.jsx
src/components/masters/programs-list/tests/ProgramListPage.test.jsx

The `<ProgramListPage />` was not wrapped with the `<WithAuthentication />` HOC, which caused the redirect to point to the LMS instead of an idp. This fixes that loop, and reworks a few tests.

Fix Redirect Loop Between LMS/Learner-Portal

---

gatsby-config.js

We don't use the site metadata anymore, and the `uuid` for the program is pulled from designer.

Remove unneeded site metadata

---

gatsby-node.js
plugins/gatsby-source-wagtail/schema/types.gql
plugins/gatsby-source-wagtail/test/mock.json
src/components/masters/program/ProgramPage.jsx
src/components/masters/program/sidebar/Sidebar.jsx

I was working off an older version of designer, and did not realize the api had changed.

Rename program homepage to external homepage

---

.env.development
gatsby-node.js
plugins/gatsby-source-wagtail/createPagesWithData.js
plugins/gatsby-source-wagtail/gatsby-node.js
plugins/gatsby-source-wagtail/templates.js
plugins/gatsby-source-wagtail/test/createPagesWithData.test.js
plugins/gatsby-source-wagtail/test/mock.json
plugins/gatsby-source-wagtail/test/mock_enterprise_page.json
plugins/gatsby-source-wagtail/test/mock_programs_pages.json
src/components/enterprise/EnterprisePage.jsx

This PR updates how pages are created during the Gatsby build to properly support both Enterprise and Programs page(s). In the end, this will not impact how pages for Masters (i.., programs, program list) are ultimately created; this is confirmed through the tests that @christopappas added.
Note: The EnterprisePage component is intentionally left sparse as the work for its UI will come in additional PR(s) (due to moving some components, e.g. course section, into the `common` folder).

Create EnterprisePage type during build

---

plugins/gatsby-source-wagtail/createPagesWithData.js
plugins/gatsby-source-wagtail/test/createPagesWithData.test.js

Because the program list page component handles the redirect to individual program page, it always need to exist even when only 1 program exists. This PR fixes that logic to ensure that page is always created during build, except in the case where an enterprise page was created first.

Always create program list page

---

src/components/common/loading-spinner/LoadingSpinner.jsx
src/components/common/loading-spinner/index.js
src/components/masters/program/ProgramPage.jsx
src/components/masters/program/main-content/ProgramMainContent.jsx
src/components/masters/program/main-content/tests/__snapshots__/ProgramMainContent.test.jsx.snap
src/components/masters/programs-list/ProgramListPage.jsx
src/components/masters/programs-list/tests/__snapshots__/ProgramListPage.test.jsx.snap

We use the same loading spinner in several places throughout the program-related pages, and will also want to reuse it for enterprise-related pages. This PR creates a `LoadingSpinner` component that is now reused in program-related pages, and can be used for enterprise pages.
It accepts a required `screenReaderText` prop for a11y.

Create reusable loading spinner component

---

plugins/gatsby-source-wagtail/createPagesWithData.js
plugins/gatsby-source-wagtail/templates.js
plugins/gatsby-source-wagtail/test/createPagesWithData.test.js
src/components/enterprise/dashboard/DashboardPage.jsx
src/components/enterprise/dashboard/main-content/DashboardMainContent.jsx
src/components/enterprise/dashboard/main-content/index.js
src/components/enterprise/dashboard/sidebar/DashboardSidebar.jsx
src/components/enterprise/dashboard/sidebar/index.js

This PR adds the initial folder structure for the enterprise pages. It also updates the Gatsby plugin to use the correct template (DashboardPage.jsx) for the root path.

Refactor enterprise folder structure

---

package-lock.json
package.json
src/components/common/with-authentication/index.js
src/components/common/with-authentication/tests/withAuthentication.test.jsx
src/components/common/with-authentication/withAuthentication.jsx
src/components/common/with-authentication/withDirectLogin.jsx
src/components/common/with-authentication/withSamlSso.jsx
src/components/enterprise/dashboard/DashboardPage.jsx
src/components/masters/program/ProgramPage.jsx
src/components/masters/programs-list/ProgramListPage.jsx

This PR extracts the common logic of withAuthentication and creates HOCs for SAML SSO and direct login capabilities. These two HOCs are then used to wrap the Program and Enterprise pages respectively.

ENT-2152 - Refactor withAuthentication to support both SAML SSO and direct login

---

src/components/masters/programs-list/ProgramListPage.jsx

Program list page would only redirect to program in it's own deployment,
which broke for the unbranded deployment. Now it takes hostname into
account

Allow for redirect to another deployment

---

package-lock.json
package.json
src/components/common/with-authentication/withAuthentication.jsx
src/components/masters/program/ProgramPage.jsx
src/components/masters/programs-list/ProgramListPage.jsx

Since there were issues with the original implementation of this ticket, we realized that we should keep the logic that determines which type of authentication mechanism to kick off based on providerSlug. This does some minor refactoring to use `compose` to wrap the Page components with `withAuthentication` and also simplifies the logic in the `withAuthentication` component.

ENT-2152 Cleanup withAuthentication

---

src/components/masters/programs-list/ProgramListPage.jsx

I noticed that the program list table was not being rendered in a Bootstrap `.container` class, such that its contents were stretched across the full width of the screen.
This PR adds in the `.container` class to the program list table view.

Add container for program list table

---

src/components/common/course-enrollments/course-cards/BaseCourseCard.jsx

For our course cards, we make an assumption that the course end date will always exist. However, it turns out the end date is a nullable field and might sometimes be empty.
This PR only renders text around the end date if an end date exists. This will prevent it from saying something like, "Ends null." when an end date is not present.
Note: I noticed this issue now that I have a valid program course enrollment on stage; the course card was saying "Ends null." Quick fix, so decided to open a PR for it :)

Only include end date in text if it exists

---

src/components/common/course-enrollments/data/__mocks__/programCourseEnrollments.json
src/components/common/course-enrollments/data/selectors.js

```
Revert "Temporary URL fix (#127)"
This reverts commit 7677060a2d4bdcf39d6773ae32e566b103aa7485.
https://github.com/edx/edx-platform/pull/21474 removes the
need to check for relative URLs from program_enrollments
API responses.
```
Reverts https://github.com/edx/frontend-app-learner-portal/pull/127
@adamstankiewicz 
(cc @edx/masters-neem )

Revert temporary URL fix, as all LMS URLs are now absolute

---

plugins/gatsby-source-wagtail/createPagesWithData.js
plugins/gatsby-source-wagtail/test/createPagesWithData.test.js
src/components/common/course-enrollments/CourseEnrollments.jsx
src/components/common/course-enrollments/data/actions.js
src/components/common/course-enrollments/data/service.js
src/components/common/course-enrollments/tests/CourseEnrollments.test.jsx

Since we've updated the enterprise enrollments api to require sending the enterprise id (https://github.com/edx/edx-enterprise/pull/561), we need to thread this variable through and update the api call tot return the proper results.

ENT-2203 Thread through enterprise id from gatsby context to enrollments call

---

src/components/common/course-enrollments/course-cards/email-settings/data/service.js

Related ticket: https://openedx.atlassian.net/browse/ENT-2271
This PR swaps out our use of the `/user_api/v1/preferences/email_opt_in/` endpoint for the correct `/change_email_settings/` endpoint.

Change the API endpoint for updating course email settings

---

src/components/common/course-enrollments/course-cards/email-settings/data/service.js

The `/change_email_settings` endpoint does not have a trailing slash like most of other endpoints we've hit in the past, causing a 404 when hitting the endpoint with the trailing slash.

Remove "/" on API url

---

gatsby-node.js
plugins/gatsby-source-wagtail/schema/types.gql
plugins/gatsby-source-wagtail/test/createPagesWithData.test.js
src/components/enterprise/dashboard/sidebar/DashboardSidebar.jsx

This PR primarily includes `contact_email` in our GraphQL query and adds `contact_email` to the GraphQL schema (so that the query doesn't break the build if `contact_email` is empty, as will be the case for program pages).
It also adds some bottom margin on the loading spinner for offers in the sidebar so there's some space between the loading spinner and the "Need help?" section.

Ensure `contact_email` comes through GraphQL

---

src/components/common/course-enrollments/course-cards/BaseCourseCard.jsx
src/components/common/course-enrollments/course-cards/styles/CourseCard.scss
src/components/common/course-enrollments/course-cards/tests/BaseCourseCard.test.jsx

This PR removes the Bootstrap columns that controlled the positioning of the course title and settings dropdown in favor of a wrapper `div` that has the `.d-flex` (`display: flex`). 
With the help of the `.flex-grow-1` and `.flex-grow-0` classes, the settings dropdown `div` will always have the width of its children whereas the course title `div` will expand the remainder of the course card that the settings dropdown does not take up.
This allows the settings dropdown button to render nicely at the top right of course cards while letting the course title fill as much space as it needs. This holds true at all screen widths.

Clean up the title/settings button UI on course cards

---

package-lock.json
package.json

This PR addresses the `npm audit` command's output that was saying we had many npm package vulnerabilities (a couple critical). I was able to resolve the majority of them by running `npm audit fix` (updates the package-lock.json file accordingly), which left just 1 manual package update to do for a dev dependency (es-check).
**Before**
**After**

Fixes npm audit output

---

src/common/features.js
src/components/common/course-enrollments/course-cards/BaseCourseCard.jsx
src/components/common/course-enrollments/course-cards/styles/CourseCard.scss
src/components/common/course-enrollments/styles/CourseSection.scss
src/components/common/layout/SidebarBlock.jsx
src/components/enterprise/dashboard/sidebar/DashboardSidebar.jsx
src/components/masters/program/sidebar/tests/__snapshots__/ProgramSidebar.test.jsx.snap

This PR hides the offers section in the Enterprise dashboard sidebar unless an `enterprise_offers` feature flag is enabled via the query parameter, e.g. "?features=enterprise_offers".
I also changed the `<h3>` and `<h5>` in the sidebar to be `<h4>`. This makes all sidebar block headings the same size (consistency!) and has slightly less visual importance than the course cards.

Sidebar offers moved behind "enterprise_offers" feature flag

---

.env.development
gatsby-config.js
src/components/common/app-context/AppContext.jsx
src/components/common/app-context/index.js
src/components/common/course-enrollments/CourseEnrollments.jsx
src/components/common/course-enrollments/course-cards/BaseCourseCard.jsx
src/components/common/course-enrollments/course-cards/InProgressCourseCard.jsx
src/components/common/course-enrollments/course-cards/mark-complete-modal/MarkCompleteModal.jsx
src/components/common/course-enrollments/course-cards/mark-complete-modal/tests/MarkCompleteModal.test.jsx
src/components/common/course-enrollments/course-cards/tests/BaseCourseCard.test.jsx
src/components/common/course-enrollments/data/actions.js
src/components/common/course-enrollments/tests/CourseEnrollments.test.jsx
src/components/common/hero/Hero.jsx
src/components/common/hero/tests/Hero.test.jsx
src/components/common/layout/Layout.jsx
src/components/common/layout/index.js
src/components/enterprise/dashboard/DashboardPage.jsx
src/components/enterprise/dashboard/main-content/DashboardMainContent.jsx
src/components/enterprise/dashboard/sidebar/DashboardSidebar.jsx
src/components/enterprise/enterprise-page/EnterprisePage.jsx
src/components/enterprise/enterprise-page/index.js
src/components/masters/masters-page/MastersPage.jsx
src/components/masters/masters-page/index.js
src/components/masters/program/ProgramPage.jsx
src/components/masters/program/sidebar/ProgramSidebar.jsx
src/components/masters/program/sidebar/tests/ProgramSidebar.test.jsx
src/components/masters/programs-list/ProgramListPage.jsx

My proposed solution for [ENT-2280](https://openedx.atlassian.net/browse/ENT-2280) involves some refactoring to add 3 new components: `AppContext`, `EnterprisePage`, and `MastersPage`. It also removes `LayoutContext` in favor of `AppContext`.
Now, `Layout` (and other components) pull from `AppContext` to get whatever configuration it needs. The value for `AppContext` is set in `EnterprisePage` and `MastersPage`. The value is meant to be an app-wide configuration, where you can pass in the `pageContext` as well as header menu items that should only apply for masters vs. enterprise, without needing to do any conditionals based on `pageType` (e.g., "pages.EnterprisePage").
This also tackles the TODO [noted here](https://github.com/edx/frontend-app-learner-portal/blob/c748b14ce06ef1c774c931440 …

App-wide configurations for enterprise and masters

---

docs/decisions/0003-graphql-schema.rst

And ADR for adding the graphql schema to gatsby to prevent type inference from failing to build pages. Please look it over when you have the chance.

ADR: graphql schema

---

src/components/common/course-enrollments/data/actions.js

This PR addresses [EDUCATOR-4688](https://openedx.atlassian.net/browse/EDUCATOR-4688). The issue was related to the recent refactor that removed the conditional checks based on page type (ProgramPage, EnterprisePage) throughout the app for both masters/enterprise, but missed one spot where this conditional check happens: https://github.com/edx/frontend-app-learner-portal/blob/master/src/components/common/course-enrollments/data/actions.js#L50.
The `options` passed into this function no longer has a `pageType` key but the code was relying on it to be able to get the `course_runs` data from the program enrollments overview endpoint response.  Instead, we can know if the call if for a program since the options object passed into the `transformCourseEnrollmentsResponse` function contains a …

Remove pageType conditional in favor of programUUID check

---

.travis.yml
Dockerfile

As part of the upgrade efforts to Node 12, this PR updates this repo from Node 8 to 12. Once this PR lands, we can update the column for this repo with a 🍑 😄- https://openedx.atlassian.net/wiki/spaces/FEDX/pages/931561855/Frontend+Repos.

fix: upgrade to Node 12

---

gatsby-config.js
package-lock.json
package.json
src/components/program/hero/styles/Hero.scss
src/components/program/styles/ProgramPage.scss

Fixing compilation issue with Gatsby by moving the font imports to a plugin; may need to update https://github.com/edx/frontend-learner-portal-base if the problem persists.

Fix Google fonts import

---

src/components/program/sidebar/Links.jsx
src/components/program/styles/ProgramPage.scss
src/components/programs-list/styles/ProgramListPage.scss

Override for the menu dropdown in the header, as well as a fix to the document dropdown which was displaying as btn-primary rather than btn-link.

Fix menu and document dropdown buttons

---

FrontendPlatformWrapper.jsx

The upgrade to @edx/frontend-platform/auth didn't take an account the need for a SSO redirect. This fixes the issue.
@edx/masters-devs-cosmonauts

fix: use idp redirect

---

FrontendPlatformWrapper.jsx
src/components/layout/Layout.jsx
src/components/programs-list/tests/ProgramListPage.test.jsx

We can track learner portal visit data in google analytics. Currently, without this fix, we can only see click events sent.

fix: Add proper tracking initialization and page track event calls

---

.env.development
gatsby-config.js
src/components/layout/Layout.jsx
src/components/notices-provider/NoticesProvider.jsx
src/components/notices-provider/api.js
src/components/notices-provider/index.js
src/components/programs-list/tests/__snapshots__/ProgramListPage.test.jsx.snap

To support the notices plugin on platform, this adds a redirect to the course home page. If a user lands on that page and has not acknowledged a notice, the user will be redirected to notice instead of the course home. The user can back out of the notice, or acknowledge it. They will continue to see the notice every time they hit any course until it is acknowledged.

Feat: MICROBA-1522 Add notices redirect to learning MFE

---

src/components/program/ProgramPage.jsx

issue found during testing. if API does not return any result tab view is rendering because the legacy view is set to false as default. the legacy view is set as default to align with existing user experience.

fix: legacy view should be viewed by default

---

package.json

Adds a repository URL to the package.json file so tooling such as Paragon Usage Insights can properly link to the Github repository.

chore: add repository url

---

src/components/program/ProgramPage.jsx
src/components/programs-list/tests/__snapshots__/ProgramListPage.test.jsx.snap

Old Behavior 
- The tabular view was based previously only if the flag `ENABLE_MASTERS_PROGRAM_TAB_VIEW` value is true. 
New Behavior 
- Since for now we only have just two tabs, rendering tabular view in case discussions are not configured feels undesirable. so now tabular view will only be visible if the tabular view flag `ENABLE_MASTERS_PROGRAM_TAB_VIEW` is turned on and discussion is configured for the program.

fix: switch to tab view only when more than one tabs are available

---

Dockerfile

[MST-1435](https://openedx.atlassian.net/browse/MST-1435)
Just want to upgrade the docker image from using node v12 to node v16.
This enables testing on local machine for using node v16 for development, and validating node v16 for stage and prod environment.

chore: upgrade local docker container to use node v16

---

.github/workflows/node-ci.yml
package-lock.json
package.json

Codecov NodeJS Uploader [package](https://www.npmjs.com/package/codecov) is depreciated since version 3.8.3
This PR move the coverage to CI according to the new guidelines and [depreciation](https://about.codecov.io/blog/codecov-uploader-deprecation-plan/) plan of codecov

Moving code coverage from codecov package to CI

---

.github/workflows/node-ci.yml

Update codecov to the latest version and start using the org-wide token for uploads.
See https://github.com/openedx/wg-frontend/issues/179

build: Update codecov and use token

---

.github/workflows/node-ci.yml
src/components/programs-list/tests/__snapshots__/ProgramListPage.test.jsx.snap

As a first step in the upgrade to Node 20, add it to the CI matrix as a non-blocking test. 
See [the tracking issue](https://github.com/openedx/frontend-app-learner-portal-programs/issues/325) for further information.
Also as a result of [renovate/edx-frontend-component-footer-edx-7.x#324](https://github.com/openedx/frontend-app-learner-portal-programs/pull/324) 2 snapshots are failing from 1 test suite, this PR also updates the snapshots to resolve that issue.

test: Add Node 20 to CI matrix

---

.github/workflows/node-ci.yml

This code does not have any dependencies that are specific to any specific
version of ubuntu.  So instead of testing on a specific version and then needing
to do work to keep the versions up-to-date, we switch to the ubuntu-latest
target which should be sufficient for testing purposes.
This work is being done as a part of https://github.com/openedx/platform-roadmap/issues/377
closes https://github.com/openedx/frontend-app-learner-portal-programs/issues/320

build: Switch to ubuntu-latest for builds

---

.github/workflows/node-ci.yml

Completed upgrade to Node 20 by removing the Node 18 CI check and using `.nvmrc` for version to use.
See [the tracking issue](https://github.com/openedx/frontend-app-learner-portal-programs/issues/325) for further information.

test: Remove support for Node 18

---

src/components/course-enrollments/course-cards/BaseCourseCard.jsx
src/components/masters-page/MastersPage.jsx
src/components/programs-list/tests/__snapshots__/ProgramListPage.test.jsx.snap

now that the legacy profile and account pages have been removed, we need to make sure that all of the links point to the MFE URLs; we were relying on the legacy applications to do redirection before.
FIXES: APER-3884
FIXES: openedx/public-engineering#71

chore: make sure links point to MFE not legacy
